### PR TITLE
Add noplayground as no_run does not seem to affect the play or copy buttons.

### PR DESCRIPTION
**Pull request by hkBst**

### CODE REVIEW

**Review by jrdngr — APPROVED** [review]

**Comment by hkBst** [comment]
Hi Jordan, thanks for merging. When I go look at https://jrdngr.github.io/pngme_book/chapter_1.html#unit-tests it still does not seem to work though. Any ideas why?

**Comment by jrdngr** [comment]
I wouldn't expect the play button to work since these are code snippets that only contain the testing code. I think you would also need the implementation logic to be present in these code blocks in order for that to work, but obviously I can't do that without giving away the answers.

The copy button does work for me.

**Comment by hkBst** [comment]
Yeah, that's what I mean :). The play button still produces a small window below the code that will say "Running..." and then be empty. The copy button also still includes the extra code necessary for that (fn main {...}) which is not in the included file. If the deployed code now uses "no_run,noplayground", then it should not do that anymore. The play button should be gone or disabled, and the copy button should only copy the code from the included file.

**Comment by jrdngr** [comment]
Oh yeah I have no idea about any of that. I took a quick look at the mdbook docs and didn't see any way to disable it.

**Comment by hkBst** [comment]
I had an idea that it could be because an old version of mdbook, and indeed the playground used to be named playpen, which is why noplayground did not have any effect. https://github.com/jrdngr/pngme_book/pull/26 should fix it.

**Pull request merged**
